# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WikiMcp < Formula
  desc "Personal wiki server with MCP integration"
  homepage "https://github.com/robert2411/wiki-mcp"
  version "0.5.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robert2411/wiki-mcp/releases/download/v0.5.1/wiki-mcp_0.5.1_darwin_amd64.tar.gz"
      sha256 "a83436ee71cebb4ca030ffb9996efae1819a007c50f33ec59939cc49e58f930c"

      define_method(:install) do
        bin.install "wiki-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robert2411/wiki-mcp/releases/download/v0.5.1/wiki-mcp_0.5.1_darwin_arm64.tar.gz"
      sha256 "5b727f3b132a2b56b063a72d91b1a36c5efccf9fd1e9e14a5a45552a385ac3a0"

      define_method(:install) do
        bin.install "wiki-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robert2411/wiki-mcp/releases/download/v0.5.1/wiki-mcp_0.5.1_linux_amd64.tar.gz"
      sha256 "a945dde7663bb347aded7d723f4f0ad6699d4b0964e63316c6cb1ae9358f891d"
      define_method(:install) do
        bin.install "wiki-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robert2411/wiki-mcp/releases/download/v0.5.1/wiki-mcp_0.5.1_linux_arm64.tar.gz"
      sha256 "37e06eceb972c5486149a3e18c881b0e58843b5bc70e10edd1f289794e839fd5"
      define_method(:install) do
        bin.install "wiki-mcp"
      end
    end
  end

  test do
    system "#{bin}/wiki-mcp", "--version"
  end
end
