# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WikiMcp < Formula
  desc "Personal wiki server with MCP integration"
  homepage "https://github.com/robert2411/wiki-mcp"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/robert2411/wiki-mcp/releases/download/v0.5.2/wiki-mcp_0.5.2_darwin_amd64.tar.gz"
      sha256 "4ef5a289f98bf55dcb236d6e08c2bdd46fae2f4fd17dd03d16a56b1d84890e32"

      define_method(:install) do
        bin.install "wiki-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/robert2411/wiki-mcp/releases/download/v0.5.2/wiki-mcp_0.5.2_darwin_arm64.tar.gz"
      sha256 "5069df55093e15d99563d82763ffedeef01f7e971ad4649232ecff431209cf6e"

      define_method(:install) do
        bin.install "wiki-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/robert2411/wiki-mcp/releases/download/v0.5.2/wiki-mcp_0.5.2_linux_amd64.tar.gz"
      sha256 "43526db4af87daf5f0b56661810a3422248ce4b0efccd65c7790769d71308546"
      define_method(:install) do
        bin.install "wiki-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/robert2411/wiki-mcp/releases/download/v0.5.2/wiki-mcp_0.5.2_linux_arm64.tar.gz"
      sha256 "9274b9cbe268b760c8247dd7c899125ec2619adcac2bf98bb9624d71fe75f4de"
      define_method(:install) do
        bin.install "wiki-mcp"
      end
    end
  end

  test do
    system "#{bin}/wiki-mcp", "--version"
  end
end
